name: Publish

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: git subtree
      run: |
        git subtree push --prefix dist origin gh-pages
